on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      # here would install libs 

      - name: Run Python Script
        run: python ci_script.py